/* Copyright 2015-2017 Jack Humbert
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "planck.h"
#include "action_layer.h"

extern keymap_config_t keymap_config;

enum planck_layers {
  _QWERTY,
  _NUMPAD,
  _MEDIAMOUSE,
  _LOWER,
  _RAISE,
  _ADJUST
};

/* Layout Documentation
 * All keyboard layout documentation is found in the keyboard-layouts directory 
 * in {my dotfiles repository on GitHub.](https://github.com/shmcgrath/dotfiles)
 * Most documentation is in json and png format and was generated by
 * [keyboard-leyout-editor.com.](http://www.keyboard-layout-editor.com/)
 * I have removed the defalt ASCII-art layout diagrams from this file.
 */

enum planck_keycodes {
  QWERTY = SAFE_RANGE,
  LOWER,
  RAISE,
};

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

[_QWERTY] = {
  {KC_TAB, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC},
  {CTL_T(KC_ESC), KC_A, KC_S, KC_D, KC_F, KC_G, KC_H, KC_J, KC_K, KC_L, KC_SCLN, KC_QUOT},
  {KC_LSFT, KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_COMM, KC_DOT, KC_SLSH, RSFT_T(KC_ENT)},
  {KC_LEAD, KC_LCTL, KC_LALT, KC_LGUI, LOWER, KC_SPC, KC_SPC, RAISE, KC_HYPR, KC_MEH, KC_ALGR, KC_RCTL}
},

[_LOWER] = {
  {KC_TILD, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL},
  {KC_TRNS,  KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_F6, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE},
  {KC_TRNS, KC_F7, KC_F8, KC_F9, KC_F10, KC_F11, KC_F12, KC_APP, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
  {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT}
},

[_RAISE] = {
  {KC_GRV, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_TRNS},
  {KC_TRNS, KC_F13, KC_F14, KC_F15, KC_F16, KC_F17, KC_F18, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS},
  {KC_TRNS, KC_F19, KC_F20, KC_F21, KC_F22, KC_F23, KC_F24, KC_MENU, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS},
  {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_HOME, KC_PGDOWN, KC_PGUP, KC_END}
},

[_ADJUST] = {
  {KC_TRNS, RESET, DEBUG, KC_TRNS, KC_TRNS, KC_NUBS, KC_NUHS, KC_TRNS, KC_TRNS, KC_SLCK, KC_PAUSE, KC_INS},
  {KC_TRNS, AU_ON, AU_OFF, KC_TRNS, KC_PSCR, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_PWR, KC_POWER, KC_EJCT},
  {KC_TRNS, QWERTY, TG(_NUMPAD), KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, TG(_MEDIAMOUSE), KC_TRNS, KC_SLEP, KC_WAKE, KC_TRNS},
  {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_BRID, KC_BRIU, KC_TRNS}
},

[_NUMPAD] = {
  {KC_TRNS, KC_NLCK, KC_UP, KC_NO, KC_LPRN, KC_RPRN, KC_PEQL, KC_P7, KC_P8, KC_P9, KC_P0, KC_BSPC},
  {KC_TRNS, KC_LEFT, KC_DOWN, KC_RIGHT, KC_NO, KC_CIRC, KC_PPLS, KC_P4, KC_P5, KC_P6, KC_PAST, KC_PDOT},
  {KC_TRNS, KC_CALC, KC_NO, KC_NO, KC_DLR, KC_PERC, KC_PMNS, KC_P1, KC_P2, KC_P3, KC_PSLS, KC_PENT},
  {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
},

[_MEDIAMOUSE] = {
  {KC_TRNS, KC_BTN1, KC_MS_U, KC_BTN2, KC_MSEL, KC_VOLD, KC_VOLU, KC_MYCM, KC_WHOM, KC_TRNS, KC_WH_U, KC_TRNS},
  {KC_TRNS, KC_MS_L, KC_MS_D, KC_MS_R, KC_MPRV, KC_MNXT, KC_MRWD, KC_MFFD, KC_TRNS, KC_WH_L, KC_WH_D, KC_WH_R},
  {KC_TRNS, KC_BTN4, KC_BTN3, KC_BTN5, KC_MSTP, KC_MPLY, KC_MUTE, KC_MAIL, KC_ACL0, KC_ACL1, KC_ACL2, KC_TRNS},
  {KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS}
}
};

#ifdef AUDIO_ENABLE
#endif

bool process_record_user(uint16_t keycode, keyrecord_t *record) {
  switch (keycode) {
    case QWERTY:
      if (record->event.pressed) {
        print("Mode: QWERTY\n");
        set_single_persistent_default_layer(_QWERTY);
      }
      return false;
      break;
    case LOWER:
      if (record->event.pressed) {
        layer_on(_LOWER);
        update_tri_layer(_LOWER, _RAISE, _ADJUST);
      } else {
        layer_off(_LOWER);
        update_tri_layer(_LOWER, _RAISE, _ADJUST);
      }
      return false;
      break;
    case RAISE:
      if (record->event.pressed) {
        layer_on(_RAISE);
        update_tri_layer(_LOWER, _RAISE, _ADJUST);
      } else {
        layer_off(_RAISE);
        update_tri_layer(_LOWER, _RAISE, _ADJUST);
      }
      return false;
      break;
  }
  return true;
}

LEADER_EXTERNS();

void matrix_scan_user(void) {
  LEADER_DICTIONARY() {
    leading = false;
    leader_end();

    SEQ_THREE_KEYS(KC_S, KC_H, KC_M) {
      SEND_STRING("Sarah H. McGrath");
    }
  }
}
